### ISSUE TITLE
BadRequest error when copying base images for buildtools-prereqs repo

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#1125]
The following exception occurs when executing the [`Copy Base Images` task](https://github.com/dotnet/docker-tools/blob/3dffba687866f8f7eef5033b4be6c0c5ca3ba961/eng/common/templates/steps/copy-base-images.yml#L9-L26) of the [check-base-image-updates pipeline](https://github.com/dotnet/docker-tools/blob/3dffba687866f8f7eef5033b4be6c0c5ca3ba961/eng/pipelines/check-base-image-updates.yml#L20-L24) for the [buildtools-prereqs repo](https://github.com/dotnet/dotnet-buildtools-prereqs-docker):

```
Microsoft.Rest.Azure.CloudException: Long running operation failed with status 'BadRequest'.
   at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.CheckErrorStatusAndThrowAsync(HttpRequestMessage request, HttpResponseMessage response)
   at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.GetRawAsync(Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.UpdateResourceFromPollingUri(Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.Poll(Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Rest.ClientRuntime.Azure.LRO.AzureLRO`2.StartPollingAsync()
   at Microsoft.Rest.ClientRuntime.Azure.LRO.AzureLRO`2.BeginLROAsync()
   at Microsoft.Rest.Azure.AzureClientExtensions.GetLongRunningOperationResultAsync[TBody,THeader](IAzureClient client, AzureOperationResponse`2 response, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Rest.Azure.AzureClientExtensions.GetLongRunningOperationResultAsync[TBody](IAzureClient client, AzureOperationResponse`1 response, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Rest.Azure.AzureClientExtensions.GetLongRunningOperationResultAsync(IAzureClient client, AzureOperationResponse response, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Rest.Azure.AzureClientExtensions.GetPostOrDeleteOperationResultAsync(IAzureClient client, AzureOperationResponse response, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ContainerRegistry.Fluent.RegistriesOperations.ImportImageWithHttpMessagesAsync(String resourceGroupName, String registryName, ImportImageParametersInner parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ContainerRegistry.Fluent.RegistriesOperationsExtensions.ImportImageAsync(IRegistriesOperations operations, String resourceGroupName, String registryName, ImportImageParametersInner parameters, CancellationToken cancellationToken)
   at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
```

[Example build failure](https://dev.azure.com/dnceng/internal/_build/results?buildId=2145280&view=logs&j=7c429c77-845f-5062-ff1f-e5558aef6320&t=3781df16-2b28-5af5-4ecf-a61974401e06) (internal link)

This only occurs for that repo, so it seems specific to the tags or registries being referenced in that repo. The log doesn't indicate which tag it is that's causing the failure. Multiple tags are output but the imports happen in parallel so it's not clear which one is the cause.

**Comment by lbussell** [comment]
@mthalman has this fixed itself? https://dev.azure.com/dnceng/internal/_build?definitionId=805&_a=summary

**Comment by mthalman** [comment]
Indeed. That's the best kind of fix.
