### ISSUE TITLE
Duplicate matrix leg name from introduction of aspnet composite Dockerfiles

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#1141]
The introduction of the [aspnet composite Dockerfiles](https://github.com/dotnet/dotnet-docker/pull/4594) have caused there to be situations where the matrix generation fails. It ends up producing duplicate leg names.

Example: https://dev.azure.com/dnceng/internal/_build/results?buildId=2189050&view=results (internal link)

```
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Duplicate leg name(s) found in matrix 'linuxArm32': 8.0-alpine3.17-aspnet
   at Microsoft.DotNet.ImageBuilder.Commands.GenerateBuildMatrixCommand.GenerateMatrixInfo() in /image-builder/src/Commands/GenerateBuildMatrixCommand.cs:line 448
   at Microsoft.DotNet.ImageBuilder.Commands.GenerateBuildMatrixCommand.ExecuteAsync() in /image-builder/src/Commands/GenerateBuildMatrixCommand.cs:line 46
   at Microsoft.DotNet.ImageBuilder.Commands.Command`2.<GetCliCommand>b__9_0(TOptions options) in /image-builder/src/Commands/Command.TOptions.cs:line 46
```

Looking at the matrix legs that were generated, I see this:

![image](https://github.com/dotnet/docker-tools/assets/15789599/7a5f0323-9f80-462b-abe1-7cf1770c48a1)

One is targeting the normal aspnet Dockerfiles and the other is for composite but they have the same leg name.

**Comment by lbussell** [comment]
This is still happening, apparently. I was able to reproduce the new instance of this happening so I am trying to get it fixed soon.
