### ISSUE TITLE
push-common-updates pipeline is silently failing with JsonReaderException

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#1219]
Not only does the exception need to be fixed but the pipeline needs to be fixed so this exception would cause a pipeline failure.

```
Unhandled exception: Newtonsoft.Json.JsonReaderException: JSON integer 2184494605 is too large or small for an Int32. Path 'items[0].id', line 1, position 534.
   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Microsoft.DotNet.VersionTools.Automation.GitHubApi.GitHubClient.SearchPullRequestsAsync(GitHubProject project, String headPrefix, String author, String sortType) in /_/src/Microsoft.DotNet.VersionTools/lib/src/Automation/GitHubApi/GitHubClient.cs:line 237
   at FilePusher.FilePusher.CreatePullRequestAsync(GitHubClient client, GitRepo gitRepo, Config config, Options options) in /file-pusher/FilePusher.cs:line 157
   at FilePusher.FilePusher.<>c__DisplayClass2_1.<<PushFilesAsync>b__0>d.MoveNext() in /file-pusher/FilePusher.cs:line 57
```

**Comment by lbussell** [comment]
This will require an update to [Microsoft.DotNet.VersionTools.Automation.GitHubApi](https://github.com/dotnet/arcade/tree/main/src/VersionTools/Microsoft.DotNet.VersionTools/Automation/GitHubApi). It has not been updated to handle GitHub IDs as longs.

**Comment by lbussell** [comment]
Filed https://github.com/dotnet/docker-tools/issues/1224 for the silent failure.
