### ISSUE TITLE
Unable to build partial build matrix for dotnet-framework-docker

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#172]
I attempted to queue a build for the dotnet-framework-docker repo only targeting the 3.5 and 4.8 images.  During the generation of the platformDependencyGraph matrix, it produced an error (see below).  

The args used for the command were `--path '3.5*' --path '4.8*'`.  So it seems to somehow be reliant on reading the other paths as part of its generation process.

```
GENERATING BUILD MATRIX
-----------------------
System.InvalidOperationException: Unable to find platform for the tag 'mcr.microsoft.com/dotnet/framework/runtime:4.7.2-windowsservercore-ltsc2016'
   at Microsoft.DotNet.ImageBuilder.ViewModel.ManifestInfo.GetPlatformByTag(String fullTagName) in /image-builder/src/ViewModel/ManifestInfo.cs:line 111
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at Microsoft.DotNet.ImageBuilder.GraphExtensions.CreateNodeList[T](IEnumerable`1 source, Func`2 getParents) in /image-builder/src/GraphExtensions.cs:line 40
   at Microsoft.DotNet.ImageBuilder.GraphExtensions.GetCompleteSubgraphs[T](IEnumerable`1 source, Func`2 getParents) in /image-builder/src/GraphExtensions.cs:line 15
   at Microsoft.DotNet.ImageBuilder.Commands.GenerateBuildMatrixCommand.AddDockerfilePathLegs(MatrixInfo matrix, IEnumerable`1 matrixNameParts, IGrouping`2 platformGrouping) in /image-builder/src/Commands/GenerateBuildMatrixCommand.cs:line 36
   at Microsoft.DotNet.ImageBuilder.Commands.GenerateBuildMatrixCommand.GenerateMatrixInfo() in /image-builder/src/Commands/GenerateBuildMatrixCommand.cs:line 198
   at Microsoft.DotNet.ImageBuilder.Commands.GenerateBuildMatrixCommand.ExecuteAsync() in /image-builder/src/Commands/GenerateBuildMatrixCommand.cs:line 26
   at Microsoft.DotNet.ImageBuilder.ImageBuilder.Main(String[] args) in /image-builder/src/ImageBuilder.cs:line 59
```

**Comment by mthalman** [comment]
This no longer repros.
