### ISSUE TITLE
Error building partial matrix when dependent image's tag doesn't match path filter

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#181]
I tried running the following command on ImageBuilder: `generateBuildMatrix --type platformDependencyGraph --manifest "manifest.json" --architecture "*" --os-type "*" --path "2.2/*/alpine3.*"` when targeting the dotnet-docker repo.

This resulted in the following exception:
```
System.InvalidOperationException: Unable to find platform for the tag 'mcr.microsoft.com/dotnet/core-nightly/runtime-deps:2.2-alpine3.9'
   at Microsoft.DotNet.ImageBuilder.ViewModel.ManifestInfo.GetPlatformByTag(String fullTagName) in /image-builder/src/ViewModel/ManifestInfo.cs:line 111
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at Microsoft.DotNet.ImageBuilder.GraphExtensions.CreateNodeList[T](IEnumerable`1 source, Func`2 getParents) in /image-builder/src/GraphExtensions.cs:line 40
   at Microsoft.DotNet.ImageBuilder.GraphExtensions.GetCompleteSubgraphs[T](IEnumerable`1 source, Func`2 getParents) in /image-builder/src/GraphExtensions.cs:line 15
   at Microsoft.DotNet.ImageBuilder.Commands.GenerateBuildMatrixCommand.AddDockerfilePathLegs(MatrixInfo matrix, IEnumerable`1 matrixNameParts, IGrouping`2 platformGrouping) in /image-builder/src/Commands/GenerateBuildMatrixCommand.cs:line 36
   at Microsoft.DotNet.ImageBuilder.Commands.GenerateBuildMatrixCommand.GenerateMatrixInfo() in /image-builder/src/Commands/GenerateBuildMatrixCommand.cs:line 208
   at Microsoft.DotNet.ImageBuilder.Commands.GenerateBuildMatrixCommand.ExecuteAsync() in /image-builder/src/Commands/GenerateBuildMatrixCommand.cs:line 26
   at Microsoft.DotNet.ImageBuilder.ImageBuilder.Main(String[] args) in /image-builder/src/ImageBuilder.cs:line 58
```

This occurs because the alpine 3.9 SDK image depends on an image with a tag of `runtime-deps:2.2-alpine3.9` but that image is built from a Dockerfile in a path that doesn't match the path filter that was provided.  The Dockerfile is for `2.1/runtime-deps/alpine3.9/amd64` but the path filter specifies 2.2 which doesn't match.

**Comment by MichaelSimons** [comment]
To achieve the desired functionality you would need to specify two `path` args:  `--path 2.1/runtime-deps/alpine3.9* --path 2.2/*/alpine3.*`

Not worth fixing since there is a way to do this today.
