### ISSUE TITLE
Make use of retry pattern when calling `docker login`

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#403]
There are a couple cases where ImageBuilder calls `docker login`.  In rare circumstances, this command can fail due to request quotas on the ACR as shown in this build output:

```
PUSHING IMAGES
--------------
-- EXECUTING: docker version  -f "{{ .Client.Version }}"
-- EXECUTION ELAPSED TIME: 00:00:00.3681717
-- EXECUTING: docker login -u dotnetdocker --password-stdin dotnetdocker.azurecr.io
Error response from daemon: Get https://dotnetdocker.azurecr.io/v2/: toomanyrequests: Too many requests. Please visit https://aka.ms/acr/skus#sku-feature-matrix to view limits of all service tiers.
-- EXECUTION ELAPSED TIME: 00:00:00.5691086
System.InvalidOperationException: Failed to execute docker login -u dotnetdocker --password-stdin dotnetdocker.azurecr.io
   at Microsoft.DotNet.ImageBuilder.ExecuteHelper.Execute(ProcessStartInfo info, Func`2 executor, Boolean isDryRun, String errorMessage, String executeMessageOverride) in C:\image-builder\src\ExecuteHelper.cs:line 80
   at Microsoft.DotNet.ImageBuilder.DockerHelper.Login(String username, String password, String server, Boolean isDryRun) in C:\image-builder\src\DockerHelper.cs:line 88
   at Microsoft.DotNet.ImageBuilder.DockerHelper.ExecuteWithUser(Action action, String username, String password, String server, Boolean isDryRun) in C:\image-builder\src\DockerHelper.cs:line 24
   at Microsoft.DotNet.ImageBuilder.Commands.DockerRegistryCommand`1.ExecuteWithUser(Action action) in C:\image-builder\src\Commands\DockerRegistryCommand.cs:line 15
   at Microsoft.DotNet.ImageBuilder.Commands.BuildCommand.PushImages() in C:\image-builder\src\Commands\BuildCommand.cs:line 281
   at Microsoft.DotNet.ImageBuilder.Commands.BuildCommand.ExecuteAsync() in C:\image-builder\src\Commands\BuildCommand.cs:line 45
   at Microsoft.DotNet.ImageBuilder.ImageBuilder.Main(String[] args) in C:\image-builder\src\ImageBuilder.cs:line 66
```

When calling `docker login` there should be retry logic to account for this scenario.

**Comment by mthalman** [comment]
This error has also shown up outside of ImageBuilder in a pipeline task that invokes `docker login` directly in the agent.  That should be fixed as well to make use of the [Invoke-WithRetry.ps1](https://github.com/dotnet/docker-tools/blob/master/eng/common/Invoke-WithRetry.ps1) script.  This is specific to the Windows legs:
https://github.com/dotnet/docker-tools/blob/be9bed465a812011fb3e4c493fd6c279ec808f47/eng/common/templates/steps/test-images-windows-client.yml#L6

The corresponding Linux path is implemented correctly to use the retry script:
https://github.com/dotnet/docker-tools/blob/be9bed465a812011fb3e4c493fd6c279ec808f47/eng/common/templates/steps/test-images-linux-client.yml#L38
