### ISSUE TITLE
Kusto ingestion error due to throttling

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#800]
There's been a handful of publish failures lately when attempting to publish the image info data to Kusto.  A retry of the publish stage usually takes care of the problem.

```
INGESTING IMAGE INFO DATA INTO KUSTO
------------------------------------
Image Info to Ingest:
"sha256:a6b7aa1e2817017528a706afa7ba3fa7c83960928cb1e6d9b69716d7de928d5c","amd64","Linux","Alpine 3.13","5.0.0-preview.6","src/monitor/5.0/alpine/amd64/Dockerfile","dotnet/nightly/monitor","2021-06-14 15:50:38"
"5.0.0-preview.6-alpine-amd64","amd64","Linux","Alpine 3.13","5.0.0-preview.6","src/monitor/5.0/alpine/amd64/Dockerfile","dotnet/nightly/monitor","2021-06-14 15:50:38"
"5.0-alpine-amd64","amd64","Linux","Alpine 3.13","5.0.0-preview.6","src/monitor/5.0/alpine/amd64/Dockerfile","dotnet/nightly/monitor","2021-06-14 15:50:38"

Image Layer to Ingest:
"sha256:540db60ca9383eac9e418f78490994d0af424aab7bf6d0e47ac8ed4e2e9bcbba","0","7","sha256:a6b7aa1e2817017528a706afa7ba3fa7c83960928cb1e6d9b69716d7de928d5c","amd64","Linux","Alpine 3.13","5.0.0-preview.6","src/monitor/5.0/alpine/amd64/Dockerfile","dotnet/nightly/monitor","2021-06-14 15:50:38"
"sha256:52bc6e9c2c0ce2577cfe630beab524bccae768f978f7cd11d4724a9c1c130947","0","6","sha256:a6b7aa1e2817017528a706afa7ba3fa7c83960928cb1e6d9b69716d7de928d5c","amd64","Linux","Alpine 3.13","5.0.0-preview.6","src/monitor/5.0/alpine/amd64/Dockerfile","dotnet/nightly/monitor","2021-06-14 15:50:38"
"sha256:b3fc8b25c1167b1a31f64a86e16347e94cb499ec09f9b1aa534ae7e3929e3572","0","5","sha256:a6b7aa1e2817017528a706afa7ba3fa7c83960928cb1e6d9b69716d7de928d5c","amd64","Linux","Alpine 3.13","5.0.0-preview.6","src/monitor/5.0/alpine/amd64/Dockerfile","dotnet/nightly/monitor","2021-06-14 15:50:38"
"sha256:7e41093e63ac2912f88085fc0b81bc9dd2c6df2cdef1a63eebfe6fae5dfa3e8c","0","4","sha256:a6b7aa1e2817017528a706afa7ba3fa7c83960928cb1e6d9b69716d7de928d5c","amd64","Linux","Alpine 3.13","5.0.0-preview.6","src/monitor/5.0/alpine/amd64/Dockerfile","dotnet/nightly/monitor","2021-06-14 15:50:38"
"sha256:dc3ac4d972f9b4092d9cd6d5e65b242a3dd5143af116404da99f66b1d49d220b","0","3","sha256:a6b7aa1e2817017528a706afa7ba3fa7c83960928cb1e6d9b69716d7de928d5c","amd64","Linux","Alpine 3.13","5.0.0-preview.6","src/monitor/5.0/alpine/amd64/Dockerfile","dotnet/nightly/monitor","2021-06-14 15:50:38"
"sha256:4ee377a2ac549c728068e48929c53ca0ed6bad9d5b5d8690b284f285b8d7a7d9","0","2","sha256:a6b7aa1e2817017528a706afa7ba3fa7c83960928cb1e6d9b69716d7de928d5c","amd64","Linux","Alpine 3.13","5.0.0-preview.6","src/monitor/5.0/alpine/amd64/Dockerfile","dotnet/nightly/monitor","2021-06-14 15:50:38"
"sha256:f7f05c064be529d23b5b23e965175ee23d94b3287a9753aa496c36ea5b69846a","0","1","sha256:a6b7aa1e2817017528a706afa7ba3fa7c83960928cb1e6d9b69716d7de928d5c","amd64","Linux","Alpine 3.13","5.0.0-preview.6","src/monitor/5.0/alpine/amd64/Dockerfile","dotnet/nightly/monitor","2021-06-14 15:50:38"

Unhandled exception: [0]Kusto.Ingest.Exceptions.DirectIngestClientException: An error occurred while attempting to ingest: 'https://u16kustoragedotnettel.blob.core.windows.net/37357f6b-bc0f-48c9-8245-6469ca80b8c9-temp-20210614/5499_Upload_DotNetDockerImageInfo_2021-06-14_16-32-50.907_37d23ef0a7c04117a6cbe6f93be03d0d.zip'. Error: 'Failed to ingest: State='Throttled', Status='The control command was aborted due to throttling. Retrying after some backoff might succeed. CommandType: 'DataIngestPull', Capacity: 36, Origin: 'CapacityPolicy/Ingestion'.', RootActivityId='1e49f832-2896-4050-af41-4dea1523684f''
Timestamp=2021-06-14T16:32:51.2868314Z
ClientRequestId=KI.KustoDirectIngestClient.IngestFromStream.f998fa22-b238-40a7-a1f5-ebc843fb27c5;e2a25c68-721f-4cd5-9d6a-8355a066fa6e
ActivityId=d7f4a31f-84de-4733-97de-b25cb5db67ad
ActivityType=KustoDirectIngestClient.IngestFromStorage
MachineName=8e08405a1cb7
ProcessName=Microsoft.DotNet.ImageBuilder
ProcessId=1
ThreadId=17
AppDomainName=Microsoft.DotNet.ImageBuilder
ActivityStack=(Activity stack: CRID=KI.KustoDirectIngestClient.IngestFromStream.f998fa22-b238-40a7-a1f5-ebc843fb27c5;e2a25c68-721f-4cd5-9d6a-8355a066fa6e ARID=d7f4a31f-84de-4733-97de-b25cb5db67ad > KustoDirectIngestClient.IngestFromStream/d7f4a31f-84de-4733-97de-b25cb5db67ad > KustoDirectIngestClient.IngestFromStorage/bff0ffb8-7c28-4229-806b-9330030f828e)
MonitoredActivityContext=ActivityType=KustoDirectIngestClient.IngestFromStorage, Timestamp=2021-06-14T16:32:51.1820395Z, ParentActivityId=d7f4a31f-84de-4733-97de-b25cb5db67ad, TimeSinceStarted=104.824 [ms]

IngestionSourceId=be24fdc9-d921-418f-9b4c-ec9ffb3bc847
IngestionSource=https://u16kustoragedotnettel.blob.core.windows.net/37357f6b-bc0f-48c9-8245-6469ca80b8c9-temp-20210614/5499_Upload_DotNetDockerImageInfo_2021-06-14_16-32-50.907_37d23ef0a7c04117a6cbe6f93be03d0d.zip
Error=Failed to ingest: State='Throttled', Status='The control command was aborted due to throttling. Retrying after some backoff might succeed. CommandType: 'DataIngestPull', Capacity: 36, Origin: 'CapacityPolicy/Ingestion'.', RootActivityId='1e49f832-2896-4050-af41-4dea1523684f'
   at Kusto.Ingest.KustoDirectIngestClient.IngestFromBlobImplAsync(StorageSourceOptions sourceOptions, KustoIngestionProperties ingestionProperties)
   at Kusto.Ingest.KustoBaseIngestClient.IngestFromBlobInnerAsync(StorageSourceOptions sourceOptions, KustoIngestionProperties ingestionProperties)
   at Kusto.Cloud.Platform.Utils.MonitoredActivity.InvokeAsync[TActivityType,TResult](TActivityType activityType, Func`1 func, String clientRequestId)
   at Kusto.Cloud.Platform.Utils.MonitoredActivity.InvokeAsync[TActivityType,TResult](TActivityType activityType, Func`1 func, String clientRequestId)
   at Kusto.Ingest.KustoBaseIngestClient.IngestFromStorageAsync(String uri, KustoIngestionProperties ingestionProperties, StorageSourceOptions sourceOptions)
   at Kusto.Ingest.KustoBaseIngestClient.IngestFromStreamImplAsync(StreamSourceOptions sourceOptions, KustoIngestionProperties ingestionProperties)
   at Kusto.Cloud.Platform.Utils.MonitoredActivity.InvokeAsync[TActivityType,TResult](TActivityType activityType, Func`1 func, String clientRequestId)
   at Kusto.Cloud.Platform.Utils.MonitoredActivity.InvokeAsync[TActivityType,TResult](TActivityType activityType, Func`1 func, String clientRequestId)
   at Kusto.Ingest.KustoBaseIngestClient.IngestFromStreamAsync(Stream stream, KustoIngestionProperties ingestionProperties, StreamSourceOptions sourceOptions)
   at Microsoft.DotNet.ImageBuilder.Services.KustoClientWrapper.IngestFromCsvStreamAsync(Stream csv, ServicePrincipalOptions servicePrincipal, String cluster, String database, String table, Boolean isDryRun) in /image-builder/src/Services/KustoClient.cs:line 37
   at Microsoft.DotNet.ImageBuilder.Commands.IngestKustoImageInfoCommand.IngestInfoAsync(String info, String table) in /image-builder/src/Commands/IngestKustoImageInfoCommand.cs:line 140
   at Microsoft.DotNet.ImageBuilder.Commands.IngestKustoImageInfoCommand.ExecuteAsync() in /image-builder/src/Commands/IngestKustoImageInfoCommand.cs:line 53
```

**Comment by mthalman** [comment]
Reopening because the issue doesn't not appear to be fixed.  Below shows the output of a recent failure.  It shows output that 1 retry is being attempted, but that's it.

```
ActivityStack=(Activity stack: CRID=KI.KustoDirectIngestClient.IngestFromStream.68ec9748-75ec-483c-b8a1-9c904a672e42;c6753a06-9a4d-4ba7-81cb-048bf2f3b7a9 ARID=0073139d-cac2-4d70-8244-548e5972ea02 > KustoDirectIngestClient.IngestFromStream/0073139d-cac2-4d70-8244-548e5972ea02 > KustoDirectIngestClient.IngestFromStorage/c0bc4532-3502-4bb3-8a51-96f3d9957808)
MonitoredActivityContext=ActivityType=KustoDirectIngestClient.IngestFromStorage, Timestamp=2021-07-01T16:00:05.1702044Z, ParentActivityId=0073139d-cac2-4d70-8244-548e5972ea02, TimeSinceStarted=111.2548 [ms]

IngestionSourceId=e02acf47-dcc5-4733-8bad-c2db3fc61ea3
IngestionSource=https://u16kustoragedotnettel.blob.core.windows.net/37357f6b-bc0f-48c9-8245-6469ca80b8c9-temp-20210701/4248_Upload_DotNetDockerImageInfo_2021-07-01_16-00-04.885_1b7ab43ae7824a3ab93c24fa3585f803.zip
Error=Failed to ingest: State='Throttled', Status='The control command was aborted due to throttling. Retrying after some backoff might succeed. CommandType: 'DataIngestPull', Capacity: 48, Origin: 'CapacityPolicy/Ingestion'.', RootActivityId='243a29c8-04f7-477c-968e-5e1041a35522'
   at Kusto.Ingest.KustoDirectIngestClient.IngestFromBlobImplAsync(StorageSourceOptions sourceOptions, KustoIngestionProperties ingestionProperties)
   at Kusto.Ingest.KustoBaseIngestClient.IngestFromBlobInnerAsync(StorageSourceOptions sourceOptions, KustoIngestionProperties ingestionProperties)
   at Kusto.Cloud.Platform.Utils.MonitoredActivity.InvokeAsync[TActivityType,TResult](TActivityType activityType, Func`1 func, String clientRequestId)
   at Kusto.Cloud.Platform.Utils.MonitoredActivity.InvokeAsync[TActivityType,TResult](TActivityType activityType, Func`1 func, String clientRequestId)
   at Kusto.Ingest.KustoBaseIngestClient.IngestFromStorageAsync(String uri, KustoIngestionProperties ingestionProperties, StorageSourceOptions sourceOptions)
   at Kusto.Ingest.KustoBaseIngestClient.IngestFromStreamImplAsync(StreamSourceOptions sourceOptions, KustoIngestionProperties ingestionProperties)
   at Kusto.Cloud.Platform.Utils.MonitoredActivity.InvokeAsync[TActivityType,TResult](TActivityType activityType, Func`1 func, String clientRequestId)
   at Kusto.Cloud.Platform.Utils.MonitoredActivity.InvokeAsync[TActivityType,TResult](TActivityType activityType, Func`1 func, String clientRequestId)
   at Kusto.Ingest.KustoBaseIngestClient.IngestFromStreamAsync(Stream stream, KustoIngestionProperties ingestionProperties, StreamSourceOptions sourceOptions)
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
Retry 1/5, retrying in 6.6088141 seconds...
Unhandled exception: System.InvalidOperationException: Failed to ingest Kusto data.

   at Microsoft.DotNet.ImageBuilder.Services.KustoClientWrapper.IngestFromCsvStreamAsync(Stream csv, ServicePrincipalOptions servicePrincipal, String cluster, String database, String table, Boolean isDryRun) in /image-builder/src/Services/KustoClient.cs:line 68
   at Microsoft.DotNet.ImageBuilder.Commands.IngestKustoImageInfoCommand.IngestInfoAsync(String info, String table) in /image-builder/src/Commands/IngestKustoImageInfoCommand.cs:line 140
   at Microsoft.DotNet.ImageBuilder.Commands.IngestKustoImageInfoCommand.ExecuteAsync() in /image-builder/src/Commands/IngestKustoImageInfoCommand.cs:line 53
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
```
