### ISSUE TITLE
In Publish, `publishImageInfo` runs unconditionally and fails, saying the manifest file is not present

### ISSUE THREAD

**Issue by dagood** [dotnet/docker-tools#832]
https://github.com/dotnet/docker-tools/blob/7f59365dd99faff417457f5042a24db373553e4f/eng/common/templates/jobs/publish.yml#L75-L93

This failed in my build when I have `noCache: true`:

```
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.FileNotFoundException: Could not find file '/tmp/imagebuilder-repos/versions/build-info/docker/[...]'.
File name: '/tmp/imagebuilder-repos/versions/build-info/docker/[...]'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at Microsoft.DotNet.ImageBuilder.Commands.PublishImageInfoCommand.GetUpdatedImageInfo(String repoPath) in /image-builder/src/Commands/PublishImageInfoCommand.cs:line 139
[...]
```

https://dev.azure.com/dnceng/internal/_build/results?buildId=1280895&view=logs&j=739bb7ec-7296-5b40-7dff-ee3297bfdaa4&t=307ab20e-da09-58a9-37fd-320ab9135ca4&l=103

At first I thought it was because I set `noCache: true`, and the problem was that the dotnet/versions repo wasn't being cloned at all. But, looking a bit into `PublishImageInfoCommand.GetUpdatedImageInfo`, I think it must have actually cloned the repo fine, but the command just can't find my imageinfo file: I haven't created one in dotnet/versions yet with the new project's name.

I'm not sure if this is a bug, or if I just need to seed the file and some docs are necessary. Adding a more descriptive error message would help, too.

For now, I've disabled the step in my local `eng/common` using a variable check, to keep it simple:
`- ${{ if ne(variables['publishImageInfo'], false) }}:`

**Comment by MichaelSimons** [comment]
[Triage] Do you require publishing without creating the image-info or is this a temporal state?  Other features like the base image update detection and build queuing and image caching requires the published image-info.  This will help inform us on the priority of fixing this if at all.

**Comment by dagood** [comment]
It's temporary, I'll definitely be wanting those features. 😄 I just wanted to work somewhat incrementally--e.g. only touch my own Git repo + ACR on the first iteration. This is just something I ran into that might be useful to future onboardings to fix, improve the error message, or document.

**Comment by MichaelSimons** [comment]
[Triage] At this point in time, this doesn't meet our bar and is not something we plan to fix.  If things change in the future and more people onboard to this infra, we would should reconsider.  Thanks for logging the issue however.
