### ISSUE TITLE
Add retry logic for any network-dependent operation

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#837]
We should do a thorough scan through the repo to find all operations that make network calls and add retry logic to handle random network failures.  These kinds of failures occur often enough that we should put some work in to mitigate them.  A recent example of such a failure is the following:

```
Unhandled exception: System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetByteArrayAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.DotNet.ImageBuilder.GitHelper.DownloadAndExtractGitRepoArchiveAsync(HttpClient httpClient, IGitHubBranchRef branchRef) in /image-builder/src/GitHelper.cs:line 127
   at Microsoft.DotNet.ImageBuilder.SubscriptionHelper.GetSubscriptionManifestAsync(Subscription subscription, ManifestFilterOptions filterOptions, HttpClient httpClient, Action`1 configureOptions) in /image-builder/src/SubscriptionHelper.cs:line 52
   at Microsoft.DotNet.ImageBuilder.SubscriptionHelper.GetSubscriptionManifestsAsync(String subscriptionsPath, ManifestFilterOptions filterOptions, HttpClient httpClient, Action`1 configureOptions) in /image-builder/src/SubscriptionHelper.cs:line 30
   at Microsoft.DotNet.ImageBuilder.Commands.GetStaleImagesCommand.ExecuteAsync() in /image-builder/src/Commands/GetStaleImagesCommand.cs:line 51
```

**Comment by mthalman** [comment]
Another example:

```
Invoke-WebRequest: /repo/dotnet-docker/eng/common/Install-DotNetSdk.ps1:38
Line |
  38 |      Invoke-WebRequest "https://dot.net/v1/$DotnetInstallScript" -OutF …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Unable to read data from the transport connection: Connection
     | reset by peer.
```
